version: '2'

services:
  app:
    build:
      context: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    environment:
      MONGODB_URI: mongodb://db:27017/assignees
      GITHUB_ID: 295a8ebdde4efebf8278
      GITHUB_SECRET: 2da83a71081c48324dbd74f747bd68e9b3b6120e
      SESSION_SECRET: s3cr3t
      GITHUB_WEBHOOK_URL: http://ed4f1a93.ngrok.io/events
    networks:
      public:
        aliases: ['assignees.dev']
      private: ~
    depends_on:
      - db

  db:
    image: mongo:3.4
    networks:
      private: ~

networks:
  public: ~
  private: ~
