version: '2'

services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      MONGODB_URI: mongodb://db:27017/assignees
      GITHUB_ID: 19383c627ba67c57fcb9
      GITHUB_SECRET: 2ecf59c031dc6f9a0dad2ac739fcf0e136f20ef7
      SESSION_SECRET: s3cr3t
      GITHUB_WEBHOOK_URL: http://assignees.dev:3000/events
      GITHUB_WEBHOOK_SECRET: Th4tIsS3cr3t
      ADMIN_IDS: 217628
    networks:
      public:
        aliases: ['assignees.dev']
      private: ~
    depends_on:
      - db

  db:
    image: mongo:3.4
    networks:
      private: ~

networks:
  public: ~
  private: ~
