version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      APP_DOMAIN: assignees.localdev
      MONGODB_URI: mongodb://db:27017/assignees
      GITHUB_ID: e31abf9f323d5fc9085e
      GITHUB_SECRET: 10bc7b2bf9fc5948812d7d565e4ef259d6550179
      SESSION_SECRET: s3cr3t
      GITHUB_WEBHOOK_URL: http://assignees.localdev:3000/events
      GITHUB_WEBHOOK_SECRET: Th4tIsS3cr3t
      ADMIN_IDS:  217628
      GITHUB_APP_ID: e31abf9f323d5fc9085e
    networks:
      public:
        aliases: ['assignees.localdev']
      private: ~
    depends_on:
      - db

  db:
    image: mongo:3.4
    networks:
      private: ~

networks:
  public: ~
  private: ~
